export const quotes = [
  "Bro, orang udah pada gaspol, kamu masih molor di kasur aja!",
  "Gagal itu ngetawain kamu, bangkit bro, kasih bukti ke mereka!",
  "Waktu gak nungguin, tiap detik kamu rebahan, musuh kamu ketawa.",
  "Mimpi kamu kabur, bro, kejar sekarang atau nyesel seumur hidup!",
  "Lemah kamu jadi bahan candaan, kuatin diri atau ambyar!",
  "Malas kamu itu jeruji, bro, kabur sekarang pake action!",
  "Dunia gak care sama kamu, raih apa yang kamu mau!",
  "Keringetan atau mewek, pilih sekarang sebelum nyesel!",
  "Gak ada yang nolong kamu, bangkit sendiri, rebut mimpi kamu!",
  "Cukup alasan, bro, dunia gak kasih ampun buat yang lelet!",
  "Kamu stuck, bro, gerak sekarang atau tenggelam dalam penyesalan!",
  "Orang lain udah di puncak, kamu masih bingung di bawah!",
  "Mimpi itu gak dateng sendiri, kejar atau cuma jadi angan!",
  "Kelemahan kamu itu beban, buang sekarang atau hancur!",
  "Waktu jalan, kamu diam, nanti cuma gigit jari!",
  "Dunia ini keras, bro, kuat atau kamu cuma jadi penutup!",
  "Malas itu racun, bro, lawan sekarang atau mati pelan-pelan!",
  "Gak ada yang peduli mimpi kamu, buktikan sendiri!",
  "Rebahan itu nyaman, tapi mimpi kamu nunggu di luar!",
  "Orang ketawa lihat kamu jatuh, bangkit kasih tamparan!",
  "Alasan cuma bikin kamu lelet, action sekarang!",
  "Mimpi kamu gak gratis, bayar pake usaha keras!",
  "Dunia gak kasih tempat buat yang lemah, kuatin diri!",
  "Waktu gak balik, bro, jangan buang sia-sia lagi!",
  "Kamu gak lelet, dunia yang kejam, gerak cepet!",
  "Mimpi itu berat, bro, angkat sekarang atau ambyar nanti!",
  "Orang lain udah menang, kamu masih nunda-nunda!",
  "Gagal itu pelajaran, tapi rebahan cuma bikin lupa!",
  "Dunia ini panggung, mainkan peranmu atau dilupain!",
  "Malas itu musuh dalam diri, kalahin sekarang!",
  "Kamu gak sendiri, tapi cuma kamu yang bisa selamatin diri!",
  "Waktu itu tikus, diam-diam nyuri mimpimu, bro, kejar!",
  "Orang sukses gak nunggu, kamu kapan mulai?",
  "Jatuh itu biasa, tapi stay di bawah itu pilihan!",
  "Mimpi kamu cuma omong kalo gak ada usaha!",
  "Dunia gak adil, bro, makanya rebut hak kamu sekarang!",
  "Malas itu kayak rawa, makin lama kamu tenggelam!",
  "Gak ada yang kasih jalan, bikin sendiri!",
  "Waktu itu pisau, lambat gerak, kamu yang kena!",
  "Orang lain udah sampai, kamu masih bikin alasan!",
  "Mimpi itu kayak bayangan, kejar atau hilang!",
  "Lemah ituyyval cuma di pikiran, buang sekarang!",
  "Dunia ini lomba, kamu gak lari, ya kalah!",
  "Rebahan cuma buat yang nyerah, kamu gak gitu!",
  "Gagal itu nyanyi kalo kamu diam aja!",
  "Waktu gak peduli perasaan kamu, gerak sekarang!",
  "Mimpi kamu nunggu, tapi gak selamanya, bro, buruan!",
  "Orang lain ketawa, kamu masih nunduk, bangkit bro!",
  "Malas itu penyakit, sembuhin pake usaha!",
  "Dunia ini gak ramah, buktikan kamu lebih kuat!",
  "Jangan cuma mimpi, bro, wujudin dengan keringat!",
  "Orang lain udah lari, kamu masih pake sepatu salah!",
  "Gagal itu cuma tes, lulusin dengan usaha!",
  "Waktu itu emas, bro, jangan buang di kasur!",
  "Mimpi besar gak cukup, butuh langkah gede!",
  "Dunia ini hutan, bro, jadi singa atau cuma semute!",
  "Malas itu parasit, buang sebelum ngisap habis semangat!",
  "Kamu bukan penutup, bro, jadi pemeran utama!",
  "Gak ada tombol undo, gerak sekarang atau nyesel!",
  "Orang sukses gak lahir dari rebahan, bro, bangun!",
  "Mimpi itu api, nyalain atau cuma jadi asap!",
  "Dunia gak kasih diskon, rebut apa yang kamu mau!",
  "Jatuh seribu kali, bangkit seribu satu kali!",
  "Waktu itu peluru, bro, jangan jadi target!",
  "Malas itu rantai, patahkan sekarang!",
  "Kamu gak lemah, cuma lupa caranya kuat!",
  "Orang lain udah finish, kamu masih di garis start!",
  "Mimpi itu burung, kejar sebelum terbang jauh!",
  "Dunia ini ring tinju, bro, lawan atau knock out!",
  "Gagal itu cuma batu, injak dan lanjut jalan!",
  "Waktu gak kasih maaf, bro, kejar apa yang penting!",
  "Malas itu kabut, bro, buang biar lihat jalan!",
  "Kamu punya cerita, tulis sendiri atau orang lain yang nulis!",
  "Mimpi itu seperti angin, bro, tangkap atau dia pergi!",
  "Dunia ini maraton, mulai lari atau ketinggalan selamanya!",
  "Gagal itu cuma halte, jangan berhenti di situ!",
  "Waktu itu seperti air, bro, genggam atau mengalir sia-sia!",
  "Malas itu bayang-bayang, lawan dengan cahaya usaha!",
  "Kamu gak kecil, bro, cuma belum buka sayapmu!",
  "Orang lain udah terbang, kamu masih takut lepas landas!",
  "Mimpi itu seperti kunci, gunakan atau pintu tetap tertutup!",
  "Dunia ini medan perang, bro, bertarung atau menyerah!",
  "Gagal itu cuma isyarat, belok ke arah usaha!",
  "Waktu itu singa, lambat gerak, kamu jadi mangsa!",
  "Malas itu seperti lumpur, tarik diri atau tenggelam!",
  "Kamu gak rapuh, cuma belum tempa diri dengan api!",
  "Orang lain udah panen, kamu masih ragu tanam benih!",
  "Mimpi itu seperti ombak, naik atau tenggelam, bro!",
  "Dunia ini lautan, belajar berenang atau karam!",
  "Gagal itu cuma awan, terbang melewatinya!",
  "Waktu itu pelari, bro, kejar atau ketinggalan!",
  "Malas itu dinding, hancurkan dengan palu usaha!",
  "Kamu punya nyali, bro, tunjukkan atau simpan selamanya!",
  "Orang lain udah menang, kamu masih takut main!",
  "Mimpi itu seperti bintang, raih atau cuma lihat dari jauh!",
  "Dunia ini arena, bro, jadi gladiator atau penonton!",
  "Gagal itu cuma bayangan, hadapi dengan cahaya kerja keras!",
];
