export const quotes = [
  "Bro, orang udah pada gaspol, kamu masih molor di kasur aja!",
  "Gagal itu ngetawain kamu, bangkit bro, kasih bukti ke mereka!",
  "Waktu gak nungguin, tiap detik kamu rebahan, musuh kamu ketawa.",
  "Mimpi kamu kabur, bro, kejar sekarang atau nyesel seumur hidup!",
  "Lemah kamu jadi bahan candaan, kuatin diri atau ambyar!",
  "Malas kamu itu jeruji, bro, kabur sekarang pake action!",
  "Dunia gak care sama kamu, raih apa yang kamu mau!",
  "Keringetan atau mewek, pilih sekarang sebelum nyesel!",
  "Gak ada yang nolong kamu, bangkit sendiri, rebut mimpi kamu!",
  "Cukup alasan, bro, dunia gak kasih ampun buat yang lelet!",
  "Kamu stuck, bro, gerak sekarang atau tenggelam dalam penyesalan!",
  "Orang lain udah di puncak, kamu masih bingung di bawah!",
  "Mimpi itu gak dateng sendiri, kejar atau cuma jadi angan!",
  "Kelemahan kamu itu beban, buang sekarang atau hancur!",
  "Waktu jalan, kamu diam, nanti cuma gigit jari!",
  "Dunia ini keras, bro, kuat atau kamu cuma jadi penutup!",
  "Malas itu racun, bro, lawan sekarang atau mati pelan-pelan!",
  "Gak ada yang peduli mimpi kamu, buktikan sendiri!",
  "Rebahan itu nyaman, tapi mimpi kamu nunggu di luar!",
  "Orang ketawa lihat kamu jatuh, bangkit kasih tamparan!",
  "Alasan cuma bikin kamu lelet, action sekarang!",
  "Mimpi kamu gak gratis, bayar pake usaha keras!",
  "Dunia gak kasih tempat buat yang lemah, kuatin diri!",
  "Waktu gak balik, bro, jangan buang sia-sia lagi!",
  "Kamu gak lelet, dunia yang kejam, gerak cepet!",
  "Mimpi itu berat, bro, angkat sekarang atau ambyar nanti!",
  "Orang lain udah menang, kamu masih nunda-nunda!",
  "Gagal itu pelajaran, tapi rebahan cuma bikin lupa!",
  "Dunia ini panggung, mainkan peranmu atau dilupain!",
  "Malas itu musuh dalam diri, kalahin sekarang!",
  "Kamu gak sendiri, tapi cuma kamu yang bisa selamatin diri!",
  "Waktu itu tikus, diam-diam nyuri mimpimu, bro, kejar!",
  "Orang sukses gak nunggu, kamu kapan mulai?",
  "Jatuh itu biasa, tapi stay di bawah itu pilihan!",
  "Mimpi kamu cuma omong kalo gak ada usaha!",
  "Dunia gak adil, bro, makanya rebut hak kamu sekarang!",
  "Malas itu kayak rawa, makin lama kamu tenggelam!",
  "Gak ada yang kasih jalan, bikin sendiri!",
  "Waktu itu pisau, lambat gerak, kamu yang kena!",
  "Orang lain udah sampai, kamu masih bikin alasan!",
  "Mimpi itu kayak bayangan, kejar atau hilang!",
  "Lemah itu cuma di pikiran, buang sekarang!",
  "Dunia ini lomba, kamu gak lari, ya kalah!",
  "Rebahan cuma buat yang nyerah, kamu gak gitu!",
  "Gagal itu nyanyi kalo kamu diam aja!",
  "Waktu gak peduli perasaan kamu, gerak sekarang!",
  "Mimpi kamu nunggu, tapi gak selamanya, bro, buruan!",
  "Orang lain ketawa, kamu masih nunduk, bangkit bro!",
  "Malas itu penyakit, sembuhin pake usaha!",
  "Dunia ini gak ramah, buktikan kamu lebih kuat!",
];
